site_name: flightlog2x
some_url: https://github.com/stronnag/bbl2kml

theme:
  name: material
  palette:
    scheme: slate
    primary: blue

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"

plugins:
  - search
  - macros

nav:
  - index.md

extra:
    inav: "[inav](https://github.com/iNavFlight/inav)"
    mwp: "[mwp](https://github.com/stronnag/mwptools)"
    bbl2kml: "[mwp](https://github.com/stronnag/bbl2kml)"
