site_name: flightlog2x
some_url: https://github.com/stronnag/bbl2kml

theme:
  name: material
  palette:
    scheme: slate
    primary: grey
    accent: dark orange
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"

plugins:
  - search
  - macros
  - with-pdf:
      cover_subtitle: Flightlog Conversion to KML/Z
      toc_level: 3
      output_path: ../bbl2kml.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      copyright: (c) Jonathan Hudson 2022

extra_css:
  - assets/extra.css
  - assets/pdf.css

nav:
  - index.md

extra:
    inav: "[inav](https://github.com/iNavFlight/inav)"
    mwp: "[mwp](https://github.com/stronnag/mwptools)"
    bbl2kml: "[bbl2kml](https://github.com/stronnag/bbl2kml)"
